#!/usr/bin/env bash
# Build PhraseLoop with in-process Apple Silicon native speech runtimes.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

if [ "$(uname -m)" != "arm64" ]; then
  echo "✗ PhraseLoop currently targets Apple Silicon (arm64)."
  exit 1
fi

ARCH_DIR="mac-arm64"
APP="dist/$ARCH_DIR/PhraseLoop.app"

echo "→ Building Next.js…"
node scripts/fix-native-rpaths.mjs
npm run build

echo "→ Preparing standalone Next.js payload…"
rm -rf .next/standalone/.next/static .next/standalone/public
cp -R .next/static .next/standalone/.next/static
cp -R public .next/standalone/public

echo "→ Packaging Electron app…"
rm -rf dist
./node_modules/.bin/electron-builder --mac dir --arm64

# electron-builder filters node_modules from extraResources. The standalone
# server needs the dependency closure generated by Next, so copy it explicitly.
echo "→ Completing standalone Next.js dependencies…"
APP_NEXT="$APP/Contents/Resources/app-next"
rm -rf "$APP_NEXT/node_modules"
cp -R .next/standalone/node_modules "$APP_NEXT/node_modules"
test -d "$APP_NEXT/node_modules/next"

echo "→ Signing native addons and PhraseLoop…"
find "$APP_NEXT/node_modules" -type f \( -name '*.node' -o -name '*.dylib' \) -exec codesign --force --sign - {} \;
codesign --remove-signature "$APP" 2>/dev/null || true
codesign --force --deep --sign - "$APP"
codesign --verify --deep --strict "$APP"

echo "→ Bundle size report…"
du -sh "$APP"
du -sh "$APP_NEXT/node_modules"/* 2>/dev/null | sort -hr | head -20 || true

echo ""
echo "✓ Done: $ROOT/$APP"
