#!/usr/bin/env bash
# Build PhraseLoop Linux AppImage package from a finalized unpacked app.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

if [ "$(uname -s)" != "Linux" ]; then
  echo "PhraseLoop Linux packages must be built on Linux."
  echo "Detected: $(uname -s) $(uname -m)"
  exit 1
fi

case "$(uname -m)" in
  x86_64|amd64)
    BUILDER_ARCH="x64"
    ;;
  aarch64|arm64)
    BUILDER_ARCH="arm64"
    ;;
  *)
    echo "Unsupported Linux architecture: $(uname -m)"
    exit 1
    ;;
esac

linux_model_roots() {
  if [ -n "${PHRASELOOP_KOKORO_MODEL_DIR:-}" ]; then
    echo "$PHRASELOOP_KOKORO_MODEL_DIR"
  fi
  if [ -n "${PHRASELOOP_DATA_DIR:-}" ]; then
    echo "$PHRASELOOP_DATA_DIR/models/native/kokoro-1.0"
  fi
  echo "${XDG_CONFIG_HOME:-$HOME/.config}/PhraseLoop/models/native/kokoro-1.0"
  echo "${XDG_DATA_HOME:-$HOME/.local/share}/PhraseLoop/models/native/kokoro-1.0"
  echo "$HOME/Library/Application Support/PhraseLoop/models/native/kokoro-1.0"
}

find_ready_kokoro() {
  local candidate
  while IFS= read -r candidate; do
    [ -n "$candidate" ] || continue
    if [ -d "$candidate" ] \
      && [ -f "$candidate/.ready.json" ] \
      && find "$candidate" -type f -name model.onnx -print -quit | grep -q . \
      && find "$candidate" -type f -name voices.bin -print -quit | grep -q . \
      && find "$candidate" -type f -name tokens.txt -print -quit | grep -q .; then
      echo "$candidate"
      return 0
    fi
  done < <(linux_model_roots)
  return 1
}

bundle_kokoro_model() {
  if [ "${PHRASELOOP_BUNDLE_KOKORO:-0}" != "1" ]; then
    return
  fi

  local source_model="$1"
  local target_models="$2"
  local target_model="$target_models/kokoro-1.0"

  echo "Bundling Kokoro voice model..."
  rm -rf "$target_model"
  mkdir -p "$target_models"
  cp -R "$source_model" "$target_model"
  test -f "$target_model/.ready.json"
  test -n "$(find "$target_model" -type f -name model.onnx -print -quit)"
  test -n "$(find "$target_model" -type f -name voices.bin -print -quit)"
  test -n "$(find "$target_model" -type f -name tokens.txt -print -quit)"
}

KOKORO_SOURCE=""
if [ "${PHRASELOOP_BUNDLE_KOKORO:-0}" = "1" ]; then
  if ! KOKORO_SOURCE="$(find_ready_kokoro)"; then
    echo "Kokoro model is not installed locally, so it cannot be bundled into the Linux download."
    echo "Open PhraseLoop once and let the voice model finish downloading, or set PHRASELOOP_KOKORO_MODEL_DIR."
    exit 1
  fi
fi

echo "Building Next.js..."
node scripts/fix-native-rpaths.mjs

# Keep Next's compiler cache, but remove deployable output so release builds
# cannot accidentally package a stale standalone server.
if [ -d .next/cache ]; then
  NEXT_CACHE_DIR="$(mktemp -d "${TMPDIR:-/tmp}/phraseloop-next-cache.XXXXXX")"
  mv .next/cache "$NEXT_CACHE_DIR/cache"
  rm -rf .next
  mkdir -p .next
  mv "$NEXT_CACHE_DIR/cache" .next/cache
  rmdir "$NEXT_CACHE_DIR"
else
  rm -rf .next
fi

npm run build

echo "Preparing standalone Next.js payload..."
rm -rf .next/standalone/.next/static .next/standalone/public .next/standalone/dist
cp -R .next/static .next/standalone/.next/static
cp -R public .next/standalone/public
NEXT_SERVER_RUNTIME_DIR=".next/standalone/node_modules/next/dist/compiled/next-server"
mkdir -p "$NEXT_SERVER_RUNTIME_DIR"
cp node_modules/next/dist/compiled/next-server/*.runtime.prod.js* "$NEXT_SERVER_RUNTIME_DIR"/
test -f "$NEXT_SERVER_RUNTIME_DIR/app-route-turbo.runtime.prod.js"

echo "Packaging unpacked Electron app..."
rm -rf dist
./node_modules/.bin/electron-builder --linux dir "--${BUILDER_ARCH}"

UNPACKED_DIR="$(find dist -mindepth 1 -maxdepth 1 -type d -name "linux*unpacked" | head -1)"
if [ -z "$UNPACKED_DIR" ]; then
  echo "Build did not produce a linux-unpacked app."
  exit 1
fi

# electron-builder filters node_modules from extraResources. The standalone
# server needs the dependency closure generated by Next, so copy it explicitly
# before creating compressed Linux package artifacts.
echo "Completing standalone Next.js dependencies..."
APP_NEXT="$UNPACKED_DIR/resources/app-next"
rm -rf "$APP_NEXT/node_modules"
cp -R .next/standalone/node_modules "$APP_NEXT/node_modules"
test -d "$APP_NEXT/node_modules/next"

bundle_kokoro_model "$KOKORO_SOURCE" "$UNPACKED_DIR/resources/models/native"

echo "Building Linux AppImage..."
./node_modules/.bin/electron-builder --linux AppImage "--${BUILDER_ARCH}" --prepackaged "$UNPACKED_DIR"

echo ""
echo "Done:"
find dist -maxdepth 1 -type f -name "*.AppImage" -print
