#!/usr/bin/env bash
# Build PhraseLoop with in-process Apple Silicon native speech runtimes.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

if [ "$(uname -s)" != "Darwin" ] || [ "$(uname -m)" != "arm64" ]; then
  echo "✗ PhraseLoop currently targets Apple Silicon macOS."
  echo "  Detected: $(uname -s) $(uname -m)"
  exit 1
fi

ARCH_DIR="mac-arm64"
APP="dist/$ARCH_DIR/PhraseLoop.app"

echo "→ Building Next.js…"
node scripts/fix-native-rpaths.mjs

# Keep Next's compiler cache, but remove deployable output so release builds
# cannot accidentally package a stale standalone server.
if [ -d .next/cache ]; then
  NEXT_CACHE_DIR="$(mktemp -d "${TMPDIR:-/tmp}/phraseloop-next-cache.XXXXXX")"
  mv .next/cache "$NEXT_CACHE_DIR/cache"
  rm -rf .next
  mkdir -p .next
  mv "$NEXT_CACHE_DIR/cache" .next/cache
  rmdir "$NEXT_CACHE_DIR"
else
  rm -rf .next
fi

npm run build

test -f .next/BUILD_ID
test -f .next/standalone/server.js

echo "→ Preparing standalone Next.js payload…"
rm -rf .next/standalone/.next/static .next/standalone/public
cp -R .next/static .next/standalone/.next/static
cp -R public .next/standalone/public
NEXT_SERVER_RUNTIME_DIR=".next/standalone/node_modules/next/dist/compiled/next-server"
mkdir -p "$NEXT_SERVER_RUNTIME_DIR"
cp node_modules/next/dist/compiled/next-server/*.runtime.prod.js* "$NEXT_SERVER_RUNTIME_DIR"/
test -f "$NEXT_SERVER_RUNTIME_DIR/app-route-turbo.runtime.prod.js"

echo "→ Packaging Electron app…"
rm -rf dist
./node_modules/.bin/electron-builder --mac dir --arm64

# electron-builder filters node_modules from extraResources. The standalone
# server needs the dependency closure generated by Next, so copy it explicitly.
echo "→ Completing standalone Next.js dependencies…"
APP_NEXT="$APP/Contents/Resources/app-next"
rm -rf "$APP_NEXT/node_modules"
cp -R .next/standalone/node_modules "$APP_NEXT/node_modules"
test -d "$APP_NEXT/node_modules/next"

echo "→ Signing native addons and PhraseLoop…"
find "$APP_NEXT/node_modules" -type f \( -name '*.node' -o -name '*.dylib' \) -exec codesign --force --sign - {} \;
codesign --remove-signature "$APP" 2>/dev/null || true
codesign --force --deep --sign - "$APP"
codesign --verify --deep --strict "$APP"

echo "→ Bundle size report…"
du -sh "$APP"
du -sh "$APP_NEXT/node_modules"/* 2>/dev/null | sort -hr | head -20 || true

echo ""
echo "✓ Done: $ROOT/$APP"
