#!/usr/bin/env bash
# Build PhraseLoop Windows installer from a finalized unpacked app.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

case "$(uname -s)" in
  MINGW*|MSYS*|CYGWIN*)
    ;;
  *)
    echo "PhraseLoop Windows packages must be built on Windows."
    echo "Detected: $(uname -s) $(uname -m)"
    exit 1
    ;;
esac

case "$(uname -m)" in
  x86_64|amd64)
    BUILDER_ARCH="x64"
    ;;
  aarch64|arm64)
    BUILDER_ARCH="arm64"
    ;;
  *)
    echo "Unsupported Windows architecture: $(uname -m)"
    exit 1
    ;;
esac

echo "Building Next.js..."
node scripts/fix-native-rpaths.mjs

# Keep Next's compiler cache, but remove deployable output so release builds
# cannot accidentally package a stale standalone server.
if [ -d .next/cache ]; then
  NEXT_CACHE_DIR="$(mktemp -d "${TMPDIR:-/tmp}/phraseloop-next-cache.XXXXXX")"
  mv .next/cache "$NEXT_CACHE_DIR/cache"
  rm -rf .next
  mkdir -p .next
  mv "$NEXT_CACHE_DIR/cache" .next/cache
  rmdir "$NEXT_CACHE_DIR"
else
  rm -rf .next
fi

npm run build

echo "Preparing standalone Next.js payload..."
rm -rf .next/standalone/.next/static .next/standalone/public
cp -R .next/static .next/standalone/.next/static
cp -R public .next/standalone/public
NEXT_SERVER_RUNTIME_DIR=".next/standalone/node_modules/next/dist/compiled/next-server"
mkdir -p "$NEXT_SERVER_RUNTIME_DIR"
cp node_modules/next/dist/compiled/next-server/*.runtime.prod.js* "$NEXT_SERVER_RUNTIME_DIR"/
test -f "$NEXT_SERVER_RUNTIME_DIR/app-route-turbo.runtime.prod.js"

echo "Packaging unpacked Electron app..."
rm -rf dist
./node_modules/.bin/electron-builder --win dir "--${BUILDER_ARCH}"

UNPACKED_DIR="$(find dist -mindepth 1 -maxdepth 1 -type d -name "win*unpacked" | head -1)"
if [ -z "$UNPACKED_DIR" ]; then
  echo "Build did not produce a win-unpacked app."
  exit 1
fi

# electron-builder filters node_modules from extraResources. The standalone
# server needs the dependency closure generated by Next, so copy it explicitly
# before creating the Windows installer.
echo "Completing standalone Next.js dependencies..."
APP_NEXT="$UNPACKED_DIR/resources/app-next"
rm -rf "$APP_NEXT/node_modules"
cp -R .next/standalone/node_modules "$APP_NEXT/node_modules"
test -d "$APP_NEXT/node_modules/next"

echo "Building Windows installer..."
./node_modules/.bin/electron-builder --win nsis "--${BUILDER_ARCH}" --prepackaged "$UNPACKED_DIR"

echo ""
echo "Done:"
find dist -maxdepth 1 -type f -name "*.exe" -print
